config_pyiot:
  mqtt:
    server_url: "broker.mqttdashboard.com"        # http://www.hivemq.com/demos/websocket-client/
    server_port: 1883
    topic_sub: "/eyrc/AaAkVbYj/iot_to_ros"
    topic_pub: "/eyrc/AaAkVbYj/ros_to_iot"
    qos: 0

    sub_cb_ros_topic: "/ros_iot_bridge/mqtt/sub"   # ROS nodes can listed to this topic to receive data from MQTT Subscription

  google_apps:
    spread_sheet_id: "AKfycbwe414et1fpdp8IgRUVZI2oPnDQP-TcwI7GtNjoBsI2ODtf0oI"
